#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov  5 11:00:56 2018

@author: atlas
"""

kind = 'LINSPACE'
npts = 10
eta = 2
et = 4

kinds = ['LINSPACE', 'CDFM', 'IPDF1', 'IPDF2']

for k in kinds:
    #plotHistogram(sinal=False, kind = k, npts=200, var = 23)    
    plotROCs(kind = k, npts = 1000, eta = 2, et = 4)
